import os
from dotenv import load_dotenv

load_dotenv()

FLASK_DEBUG = os.getenv('FLASK_DEBUG')
SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URL')
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = os.getenv('SECRET_KEY')
WTF_CSRF_ENABLED = True

FLASK_ADMIN_SWATCH = 'solar'

OPENAPI_URL_PREFIX = '/api/docs'
OPENAPI_VERSION = '3.0.0'
OPENAPI_SWAGGER_UI_PATH = '/'
OPENAPI_SWAGGER_UI_VERSION = '3.22.0'